version: "3.9"
services:
  db:
    image: postgres:16
    container_name: herculesbet_db
    environment:
      POSTGRES_USER: hercules
      POSTGRES_PASSWORD: hercules
      POSTGRES_DB: herculesbet
      TZ: Europe/Budapest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: herculesbet_adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:

